### PR TITLE
Auto-generated @type t 

### PR DESCRIPTION
**Pull request by tim2CF**
New functionality that will generate @type notations for protobuf messages and enums

### CODE REVIEW

**Comment by pallix** [comment]
Very nice!! Could you maybe add some unit tests if you have time?

**Comment by tim2CF** [comment]
Thanks! 
Maybe, if @bitwalker is interested to merge it and push new version to hex.pm ;)
Maybe this code needs some improvements, but currently we are just using these auto-generated typespecs in our projects as is

**Comment by pallix** [comment]
How specific are the type definitions of the structs? I can swap different struct in a function definition and dialyzer do not complain.

**Comment by tim2CF** [comment]
@pallix Dialyzer is better than nothing, but unfortunately Dialyzer itself is not very strict tool. Type definitions should be ok and strict, the problem is how Dialyzer is working with specs in some cases. Here is a little research (slideshow) regarding Dialyzer weakness

https://timcf.github.io/erlang-universe/5-elixir-static-types.html#1

**Pull request merged**
