### PR TITLE
Load multiple protobuf files

### PR DESCRIPTION
**Pull request by mmmries**
#30 stalled out because it introduced several breaking changes. This is a much smaller PR that introduces just a single breaking change and a single new feature. Let's see if we can eat this :elephant: one bite at a time.

This branch replaces the `import` parsing feature with the ability to specify a list of files in the `from_file` option. No changes have been made to `inject` or to the way module names are handled. Those new features will be handled in separate PRs where we can debate those ideas separately.

/cc @DylanGriffith @bitwalker

### CODE REVIEW

**Comment by bitwalker** [comment]
Could you clarify the breaking change?

**Comment by mmmries** [comment]
I've removed the handling of "imports" in message definitions. That is the
breaking change.

**Comment by bitwalker** [comment]
@mmmries Ah, right. So if people are relying on `import` today, what would be their upgrade path?

**Comment by mmmries** [comment]
They would pass the imported file in the list of files when they call "use
protobuf". That would allow them to use the messages from both files.

**Comment by bitwalker** [comment]
It seems like the two are different features though, are they not? For instance, `use Protobuf` with multiple files or `use Protobuf` with a single file which itself has imports for other files should in theory behave the same. Was there a roadblock that prevented this from being possible? If so maybe there is a way we can work around it.

Apologies for going back and forth so much on this, I would really like to get these changes merged, but I just want to make sure we're not making breaking changes that we either don't need to make, or because the effort to avoid them is significant, without at least doing my due diligence first. Especially if we're running into issues adding features because of the way I've written the code.

**Comment by mmmries** [comment]
@bitwalker I appreciate your concern for users of the library. I hope the maintainers of the other libraries I use are just as considerate. Nothing but :heart: and appreciation from me :smile: 

I couldn't see a good path forward keeping both of them in because there was no flag to disable the handling of imports, but the way there were handled involved renaming things so if I handled the import in the parser AND imported the full list of files I would end up with multiple representations of the same protobuf definitions. This opened the door for weird edge cases like:

```elixir
%Message{nested_message: %NestedMessage{x: 15}} = Message.decode(encoded_binary)
# => BadMatchError because the nested type gets decoded to renamed module/struct
```

This goes along with #21 where other people brought up some issues with the existing way of handling imports. I didn't think I could support that existing functionality and this new functionality so I went with the breaking change.

**Comment by bitwalker** [comment]
@mmmries I appreciate your tolerance of my meddling! ;)

Is it possible to deduplicate the list of parsed definitions before doing anything with namespaces? I really need to find some time to dig in and play with it myself, but since my time is a bit tied up at the moment, I'm asking you all the questions I'd be investigating myself and hoping you have the answers :P. It may be that my question needs to be scoped to injected vs non-injected context, and if so, let's pick the one you think is most valuable at the moment and focus our attention there.

One thing in the back of my mind the past few days that I've been thinking more about is that perhaps cleaning up `exprotobuf` by choosing one way of importing definitions would help reduce overall complexity and make the library easier to use in general, i.e. designing it so that you just throw a call to `use Protobuf` in a new file and it imports everything at the top-level, somewhat like you wanted to do in your previous PR. Right now it's not clear to me when someone would use inject vs not, and what the average user of `exprotobuf` is doing, but it is clear to me that the difference is somewhat arbitrary, in the sense that I don't think the choice adds a great deal of value. I'd rather pick a path and simplify the implementation if I have to make breaking changes.

All of that doesn't really add a whole lot to this PR, but at least you know where my mind is at, and can point me in the right direction if I'm off on a tangent.

**Comment by mmmries** [comment]
@bitwalker I'm not sure if gpb does any deduplicating itself, but I know it verifies that all the nested types you have references are actually present when you call `:gpb.post_process_all_files/2` so maybe it would be handled there?

That would be a way to continue supporting `import` while adding support for multiple files, I'm just not sure how deep that :rabbit2: hole is. The reason I didn't dive down there was because of what you mentioned supporting just one way of loading a set of definitions seemed much simpler to me than trying to make multiple different mechanisms work together. That's also why I brought up the question of whether this feature really fits in `exprotobuf` or whether I should attempt it in a separate project.

The core use case that I'm thinking about with these changes is for a team of people who are already using, or plan to use, multiple languages in their system. I think that is the main reason you would pick something like `protobuf` as your data exchange format. And I think that team of people will in most cases want `exprotobuf` to work similarly to how the libraries work for python, java, ruby, etc.  In each of those cases you point the `protoc` binary at a list of `.proto` files and specify import paths as neccessary. Then protoc does all the parsing, verification and resolving of names before passing it to the code generator for your specific language. Obviously `gpb` already breaks from that workflow a little bit, and I like the idea of combining the compile step for my elixir code with the compile step for my protobuf definitions, but I still want to use point it at a whole group of files and just load them all into my runtime with a naming convention that follows the names of my message definitions.

I'm not sure if that is the intended audience for `exprotobuf`, but that is who I was thinking of when I made these changes. And for that audience I think features like `inject` and automatic handling of imports don't matter very much since those aren't tools that they will be using to generate code for the other languages.

**Comment by mmmries** [comment]
Sorry for that super long comment. I should trying being a novelist sometime. If you want me to take a stab at keeping support for automatically loading `import`s and including/deduplicating those defintions with the ones specific in the list of protobuf files I'm willing to take a stab at it.

Just didn't want to spend the time unless you really like the idea of keeping both mechanisms in place.

**Comment by DylanGriffith** [comment]
@mmmries "The core use case" you describe is what we're doing and that was one of the reasons I found it quite hard to integrate with this library particularly. I ended up forking because it seemed like the intended use of this library was significantly diverged from that way of thinking about the problem but it would be good if we could have both assuming that there are many people doing it the other way.

**Comment by bitwalker** [comment]
@mmmries After dwelling on your comments over night, I agree with the conclusion you arrived at. I'm cool with making the breaking change, since it seems like it will bring things more in line with the common use case. Would you be willing to update the README documenting how to use the feature? Once that's set, I'll go ahead and merge this, but hold off on releasing it until some of your other PRs have had a chance to get reviewed.

**Comment by mmmries** [comment]
@bitwalker I'll add a README update to this branch. Hopefully I can get it done tonight. Thanks again for all the feedback on this. This PR (and its buddies) will leave the project in a much better place than my first PR.

**Comment by mmmries** [comment]
I added a README section to this PR, but it just documents the multiple files feature which is pretty minimal. Do we want to also remove the sections on `inject` and `use_in`? I sounds like we are moving away from those features, but I don't have a need to remove them now.

Maybe we could stop documenting them in a separate PR and come up with a deprecation plan?

Also should I write up some notes about dropping support for automatic `import`s and how to replace that functionality?

**Comment by mmmries** [comment]
@bitwalker @DylanGriffith I went ahead and wrote up some specific notes about the removal of the imports feature and how to replace it by loading multiple protobuf files. I also referenced that from the top of the README so people could easily find it.

Let me know if this documentation looks good to either of you.

**Pull request merged**
