### PR TITLE
fixed string decoding (inside oneof)

### PR DESCRIPTION
**Pull request by amatalai**
As far as I remember `repeated` can't be used inside `oneof`, so only list we can get inside oneof is character list (string field).

#71

### CODE REVIEW

**Comment by bitwalker** [comment]
Just to be sure, can you find the reference for this restriction in the spec? I'm happy to merge this, just don't want to do it if it breaks things unexpectedly.

**Comment by amatalai** [comment]
Yup, here it is:

https://developers.google.com/protocol-buffers/docs/proto#oneof

> You then add your oneof fields to the oneof definition. You can add fields of any type, but cannot use the required, optional, or **repeated** keywords.

**Comment by bitwalker** [comment]
Thanks!

**Comment by bitwalker** [comment]
I'll get a new release published today hopefully

**Pull request merged**
